DROP TABLE IF EXISTS PERSON;

CREATE TABLE IF NOT EXISTS PERSON (
      id INT AUTO_INCREMENT PRIMARY KEY,
      lastname VARCHAR(250) NOT NULL,
      firstname VARCHAR(250) NOT NULL,
      zipcode INT NOT NULL,
      city VARCHAR(250) NOT NULL,
      color VARCHAR(250) NOT NULL
);

